apiVersion: apps/v1
kind: Deployment
metadata:
  name: hertz-app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hertz-app-staging
  template:
    metadata:
      labels:
        app: hertz-app-staging
    spec:
      containers:
      - name: app
        image: myusername/hertz-app:staging-latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
