apiVersion: apps/v1
kind: Deployment
metadata:
  name: hertz-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hertz-app-prod
  template:
    metadata:
      labels:
        app: hertz-app-prod
    spec:
      containers:
      - name: app
        image: myusername/hertz-app:prod-1.0.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
